### ISSUE TITLE
get rid of keys: [] when empty

### ISSUE THREAD

**Issue by donvipre** [while-true-do/ansible-role-users#1]
### Type of Report

enhancement

### Actual behaviour

keys needs to be declared even if empty.
Maybe there is a way to get rid of that empty keys: [] array when not needed.
```yaml
wtd_users:
  - name: test
    keys: []
```
### Expected behaviour
```yaml
wtd_users:
  - name: test
```
